### ISSUE TITLE
Share video from Youtube app to Newpipe

### ISSUE THREAD

**Issue by nicozimmermann94** [theScrabi/NewPipe#101]
Is there any way to view a video in newpipe coming from the stock youtube app? I want to watch videos from my subscription box. Maybe add an way to let the video "share" to newpipe?

**Comment by medavox** [comment]
Off the top of my head, you could probably use the Youtube app to fire intents to watch videos, which NewPipe then handles. You'd have to keep from registering a default Youtube video handling app, though.

You can probably do this now. Just browse videos with the Youtube app, and when you tap on one to play it (as long as there isn't a default app set), you can select NewPipe from the Choose An App menu that pops up.

**Comment by theScrabi** [comment]
Well i think the "share" idea is not that bad. People could watch videos via stock youtube app, and listen, or download them via NP.

**Comment by razzintown** [comment]
So is there no way to get NewPipe into the "Share menu"?

**Comment by theScrabi** [comment]
There is xD it just needs to be implemented :)

**Comment by theScrabi** [comment]
https://github.com/theScrabi/NewPipe/issues/84

**Comment by eighthave** [comment]
Its easy to get NewPipe in the *Share* menu (aka `ACTION_SEND`) the question is whether that is a good user experience.  The *Share* menu is supposed to be for sharing content as in messaging.  It is not supposed to be a way to hack around the normal ways of viewing.

**Comment by theScrabi** [comment]
Hm I think if some request this feature and some reject it, we should vote for this.

**Comment by nicozimmermann94** [comment]
@eighthave What about Dropbox? Most of the times it is in the share menu and I think it is not necessary messaging content.

**Comment by eighthave** [comment]
Dropbox makes sense for Share/ACTION_SEND since you're sending content
to it, which it then stores.  NewPipe does not store anything or send
messages.  It shows videos.  And for that there is the ACTION_VIEW Intent.

**Comment by ildar** [comment]
Very easy: Easy Open Link (Open URLs via select and share) - https://f-droid.org/app/de.audioattack.openlink

**Comment by theScrabi** [comment]
Problem solved, or considered as workaround?

**Comment by eighthave** [comment]
I consider this issue solved. Granted, the way Android handles the difference between Share/`ACTION_SEND` and view/`ACTION_VIEW` is not always great, but I don't think that's a problem that NewPipe can solve.
