### ISSUE TITLE
Videoder: What is it? Do they violate GPL?

### ISSUE THREAD

**Issue by timofonic** [theScrabi/NewPipe#103]
Hello.

I found a somewhat "similar" app for Android. They don't release the source code, despite they have a GitHub repository.

https://www.videoder.net
https://github.com/videoder/
http://sourceforge.net/projects/videoder/

Kind regards.

**Comment by theScrabi** [comment]
Well the design is nice. We could try to somehow stick to that. But the rest is not very useful :/

**Comment by chschtsch** [comment]
But how would he violate GPL?

**Comment by JasperWeiss** [comment]
The design is awesome though

**Comment by theScrabi** [comment]
I searched for a licence for this app, and I searched for the code of this app, and I couldn't find anything. So I assume this app is **NO** FLOSS software. Therefore I think it's very unlikely that they violate the GPL, except they use code under the GPL and didn't mark it.
