### ISSUE TITLE
Bug: Date of upload shows one month in the future

### ISSUE THREAD

**Issue by anoadragon453** [theScrabi/NewPipe#104]
Title. Happens on all videos, persists after closing and opening app.

Funnily enough, app correctly shows "Uploaded 1 day ago" in the search view, even though the video view reports it as being uploaded one month in the future.

Using version 0.6.0 from F-droid. CyanogenMod 12.1.

**Comment by chschtsch** [comment]
Good point!
But it's been fixed in #102, although not yet released. Stay tuned for upcoming release, or build the newest version yourself!

**Comment by anoadragon453** [comment]
Great to hear!
