### ISSUE TITLE
[Feature request] Auto-play on intent.

### ISSUE THREAD

**Issue by MiningMarsh** [theScrabi/NewPipe#11]
This app is already fantastic!

A nice option would be to auto-play videos when opened from an external app, i.e. when I click on a youtube link in reddit, directly start playing the video so that I don't have to hit the play button when NewPipe comes up.

**Comment by theScrabi** [comment]
All right, i added this funktion. But i think in order to make it work proper we also need the "choose stream automatically" feature.
