### ISSUE TITLE
Green Arrow appears over uploader's avatar

### ISSUE THREAD

**Issue by anoadragon453** [theScrabi/NewPipe#112]
Green arrow seems to position itself over uploader's avatar in both landscape and portrait mode.

[Images](http://imgur.com/a/OkIc6)

LG G3, CM 12.1, NewPipe f-droid build 0.6.1

**Comment by chschtsch** [comment]
Yeah, I already work on it. I will fix it soon, and push, also bringing CardView design to video list items.

**Comment by theScrabi** [comment]
Thanks for taking care about bugs I made :)

**Comment by theScrabi** [comment]
It seams like I fixed it :) please review.
