### ISSUE TITLE
Feature: OrBot/Proxy Support

### ISSUE THREAD

**Issue by Warr1024** [theScrabi/NewPipe#113]
Add settings for an http proxy host/ip and port (optionally default to 127.0.0.1:8118 for orbot when enabled).  Send all traffic through the proxy when enabled.

Use NoRootFirewall to test and confirm that traffic is not ignoring the proxy (traffic to orbot should not cause NoRootFirewall to ask for access).

Preferably avoid sending any identifying information over the network, except per explicit user request (e.g. if user provides login credentials).

**Comment by theScrabi** [comment]
https://github.com/theScrabi/NewPipe/issues/39

**Comment by theScrabi** [comment]
But if you are interested, know Android/Java, and have time, you can always help us set up that feature. :) So if you like you can join our slack group: http://invite.chschtsch.ml/
