### ISSUE TITLE
[feat req] Cancel download

### ISSUE THREAD

**Issue by spectas** [theScrabi/NewPipe#13]
Hi, thanks for this app, I like it! Additionally it would be nice to be able to cancel a download once it is started. Thanks a lot! Spectas

**Comment by theScrabi** [comment]
Well Downloading is a bigger topic. I need to rework that completely. At the moment NP is using the build in Download Manager. So a workaround would be to enter the Download Manager while downloading, ant Cancel the Download there.

**Comment by satiricon** [comment]
This is already covered by #285.
