### ISSUE TITLE
persistent notification 

### ISSUE THREAD

**Issue by JasperWeiss** [theScrabi/NewPipe#132]
Playing audio only in the background enables a persistent notification, which, cannot be removed. There should be an x on the notification to quit it.

**Comment by theScrabi** [comment]
We noticed that andoird 5+ doas not display a generic button for closing any more.

**Comment by 912d** [comment]
On 4.4.4 there is that option:
!(kitkat)[ http://i.imgur.com/MfF076h.jpg]

**Comment by theScrabi** [comment]
Right. But google thought it would be funny to just throw it out on android 5.

**Comment by medavox** [comment]
I'll sorry this out some time this week, unless anyone else would like to write a custom layout for the notification?

**Comment by theScrabi** [comment]
I was able to fix it:https://github.com/theScrabi/NewPipe/commit/7dadb2b26c7b3409527da3d1a0dc5fca58e9c99a
However the fix is not perfect. medavox you might have to lock over it again. I was not able to get the bigContentView visible. So only the small version of the notification shows up :/

**Comment by medavox** [comment]
OK from tomorrow everything should be back to normal for me, so I'll take a look then.

**Comment by medavox** [comment]
I did find a small bug in the SDK version 21+ code, but it's more difficult for me to test this, as I don't have a 5.0 device. I'll try with a emulator tomorrow.

**Comment by theScrabi** [comment]
I am also restricted to emulator, when it's about running android 5+ devices.

**Comment by JasperWeiss** [comment]
I'm running Android 5.0, Anything I can help with?

**Comment by theScrabi** [comment]
You could try to figure out why the BackgroundPlayer notification is always the small, never the big one on android 5+.

**Comment by JasperWeiss** [comment]
I'll try :)

**Comment by JasperWeiss** [comment]
It seems it fixed itself magically :D

**Comment by theScrabi** [comment]
What :P can you past a screenshot?

**Comment by JasperWeiss** [comment]
http://imgur.com/WWSeqMp

I'm assuming that's what you mean with the big one

**Comment by theScrabi** [comment]
nnnice :)
