### ISSUE TITLE
webTube: New app or fork?

### ISSUE THREAD

**Issue by timofonic** [theScrabi/NewPipe#138]
Hello.

I was looking for some FOSS Pushbullet alternative that don't rely on a centralized server. 

While I was looking for it, I saw webTube on the list of latest apps.

I asked myself why to make another app instead making this one better. It seems unneeded duplication to me.

https://github.com/martykan/webTube

Kind regards.

**Comment by theScrabi** [comment]
As it seams WebTube is simply a web frame for the Youtube Mobile website.

**Comment by timofonic** [comment]
I see...

I ended looking at the source code and it's very simple!

I also looked at the bug tracker:

https://github.com/martykan/webTube/issues/1
https://github.com/martykan/webTube/issues/3

I'm sorry. These days I overreact to copycats and license violations because there's still a lot of them :(

**Comment by theScrabi** [comment]
No problem, may happen ;). Just try to look twice in the future.
