### ISSUE TITLE
Background music doesn't stop if you launch a video normally

### ISSUE THREAD

**Issue by Dostoi** [theScrabi/NewPipe#159]
If you first launch a music in the background then want to launch one normally, the background music continue to play and superpose with the one in the foreground.
The background should stop or at least pause if you launch another one in the foreground.

**Comment by theScrabi** [comment]
Hm you are right.

**Comment by nado** [comment]
I dont know if its linked, but when I play a music in background, I have to start it before it plays (normal until that point), but then, it begins playing in background AND foreground. AKA I have a slight delay between the same video playing in background and foreground at the same time.

**Comment by Dostoi** [comment]
What do you mean by starting it before play ?
You clic on the background button then launch the video in the foreground ?
If so, you don't have to do that. Just tap on the background button and the sound is going to be played after a few seconds

**Comment by nado** [comment]
Oh, thanks, I didnt use it correctly then.

**Comment by Fymyte** [comment]
Hi, I see it is a very old issue. I was wondering if it was possible to add this as a functionality. It would be very nice to have the ability to keep a background music playing while having say a cooking recipe playing in the foreground (not managed by newpipe, more YouTube, or a video playing in the browser). I know some music player have this feature managed by a switch in the settings. See https://android.stackexchange.com/questions/125250/how-to-have-two-applications-play-sound-simultaneously.
I have no idea if this is still possible with android 12 tho.
Best regards and thanks for this app, using it everyday, and it is a real pleasure 👍. Now installed on every phone off my family.

**Comment by opusforlife2** [comment]
Please open a new feature request. 😄
