### ISSUE TITLE
version 0.7.3 crash on Android 4.0.3

### ISSUE THREAD

**Issue by digi-owl** [theScrabi/NewPipe#161]
0.7.3 fails to launch, while 0.7.2 works fine, on a tablet running Android 4.0.3.

**Comment by lhark** [comment]
Similar problem here on 4.0.4 : the app crashes when i try to search for any string.

**Comment by digi-owl** [comment]
Just installed 0.7.4 here, and so far no crashes.

**Comment by theScrabi** [comment]
Ok so maybe it was related to the UI. I didn't test it on 4.0.x yet.
