### ISSUE TITLE
Impossible to install on a g4 with stock rom lollipop 

### ISSUE THREAD

**Issue by Lucciniolo** [theScrabi/NewPipe#170]
Hello, 

It is impossible for my to install the application with fdroid. 

How can I do please?

**Comment by theScrabi** [comment]
You have to be more detailed about whats happening.

**Comment by Lucciniolo** [comment]
Hello, thanks.

When I click on "install" the progress bar try to start and it fails. Then
it is written : not installed.

In French.

**Comment by theScrabi** [comment]
Hm can you provide a log of that. Also what android version are you using?

**Comment by Lucciniolo** [comment]
Android 5.1

Where can I find them?

**Comment by Lucciniolo** [comment]
I just update fdroid and accepted instable releases in preferences and it
works!

Best regards

Le mer. 10 févr. 2016 00:33, AMARI Sofiane <amari.sofiane@gmail.com> a
écrit :

> Android 5.1
>
> Where can I find them?
>
> Le mar. 9 févr. 2016 12:32, Christian Schabesberger <

**Comment by theScrabi** [comment]
ok nice.
