### ISSUE TITLE
Download broken across versions 

### ISSUE THREAD

**Issue by cdt35** [theScrabi/NewPipe#171]
Attempting to use the download feature on Nexus 7 (2013) , Android 6.0 nonroot results in the application crashing. This affects all 0.7.x versions, which is strange. Uninstalling the app or clearing system cachd did not do anything. Changing download directories didn't do anything different either, and yes the storage permission is granted. The download feature has worked many times before, but stopped worked all of a sudden. Background play is also affected by this

**Comment by waqas** [comment]
Same here on Samsung Galaxy. "Unfortunately, NewPipe has stopped."

**Comment by theScrabi** [comment]
It's the crawler, youtube has changed their website, and NewPipe can't handle that. We have something like this from time to time. This time its bigger, but I'm already half way through. If everything works right the update should be available on f-droid the next few days. The only problem right now is that the master branch is still a bit unstable :/

**Comment by Inphi** [comment]
```It's the crawler, youtube has changed their website, and NewPipe can't handle that.```
I can still only play a video using an external player.

**Comment by theScrabi** [comment]
Yup, there is some weird stuff going on. Somehow the UI evaluates audiostreams, when someone hits the download button. Since it can't get audiostreams, a NullPointerExeption breaks the App. In the future I need to fix that to. But for now I've already made a quick and dirty solution, witch will be online the next two days.

**Comment by theScrabi** [comment]
Ok it seems I got it fixed. version 0.7.4 is rolled out, and should be online by tomorrow. This version although has some other bugs I'm aware of, but could not fix because it had to go fast, so further versions will be comming after.
