### ISSUE TITLE
NewPipe crashing when I use the background play feature

### ISSUE THREAD

**Issue by 1excellent** [theScrabi/NewPipe#172]
My main reason for using NewPipe is listening to youtube videos in the background. It's worked before, but ever since last night, every video I play with background play has crashed saying NewPipe has stopped working. Is this happening for anyone else? I'm using the F-Droid version of NewPipe

**Comment by theScrabi** [comment]
https://github.com/theScrabi/NewPipe/issues/171

**Comment by Zanthas** [comment]
Its happening for me as well. I think its something YouTube changed on their end. Download does not work for me either.
