### ISSUE TITLE
Background Music unplayable; stock Nexus 5X

### ISSUE THREAD

**Issue by FranzLiebkind0** [theScrabi/NewPipe#177]
Video feature works perfectly well, but the background music option is unplayable/unlistenable.

I press the headphones button and I get 1 to 2 seconds of the song, followed by silenced for a few seconds, followed by 1 to 2 seconds of a completely unexpected part of the song, rinse, repeat.

Nexus 5X stock

**Comment by Dekztar** [comment]
Exact same problem on my Moto X Play

**Comment by mykongee** [comment]
Same problem on my Nexus 6.

**Comment by medavox** [comment]
Could anyone please provide an error log?

**Comment by FranzLiebkind0** [comment]
Changing "Default audo format" from m4a to WebM fixes this issue.

**Comment by Dekztar** [comment]
Confirming that changing "Default audo format" from m4a to WebM did fix this issue on my Moto X Play

**Comment by mykongee** [comment]
Worked for me as well.

**Comment by theScrabi** [comment]
This may be the same reason: https://github.com/theScrabi/NewPipe/issues/191
