### ISSUE TITLE
Some searches show network error

### ISSUE THREAD

**Issue by Stevko-sk** [theScrabi/NewPipe#178]
For some searches I get network error. For example when I search word _young_. It shows no results, just bubble saying Network error. Searching for other things (for example for word _old_) shows results as expected.

**Comment by ZatsuneNoMokou** [comment]
For me, tried RWBY, it work when I leave the content language in en, but I get network error in I put it in French

**Comment by prashantchawla** [comment]
young is magical. same behavior on my phone too. :P

**Comment by theScrabi** [comment]
@ZatsuneNoMokou: confirmed.

**Comment by theScrabi** [comment]
Ok should be fixed by now.

**Comment by Magissia** [comment]
Was able to reproduce on 0.7.5

**Comment by prashantchawla** [comment]
What keyword did you search?

**Comment by Magissia** [comment]
Tried to search gris, but wasn't able to reproduce on current version ( 7.6)

**Comment by theScrabi** [comment]
Well there where livestrams in the list of results a few days ago. NP could not handle live stream items. Now it can.
