### ISSUE TITLE
Play in Background Setting (Headphone) crashes the App

### ISSUE THREAD

**Issue by TGuptaNYC** [theScrabi/NewPipe#179]
^

Running a Moto G (2nd Gen)

**Comment by chaitanyanettem** [comment]
+1

**Comment by theScrabi** [comment]
Please provide a log.

**Comment by prashantchawla** [comment]
[2016-02-16-00-45-15.txt](https://github.com/theScrabi/NewPipe/files/131310/2016-02-16-00-45-15.txt)

Here.

**Comment by xiorcal** [comment]
use to have that bug too; but it magically disapear... if i got it again how to i export the log?

**Comment by prashantchawla** [comment]
1) Install 'CatLog' app.
2) Open it and select Options -> Record.
3) Reproduce the bug.
4) Then select Options -> Stop Recording.

**Comment by chaitanyanettem** [comment]
The apk in f-droid had the issue. When I built from the master branch today I didn't face the issue.

**Comment by theScrabi** [comment]
Is it still crashing on 0.7.4?

**Comment by prashantchawla** [comment]
Although, this particular log was from 0.7.3 & after updating to 0.7.4, I'm able to play most of the videos in background, I've still seen one or two crashes after updating. Will provide a log soon if I'm able to reproduce.

**Comment by theScrabi** [comment]
Ok thanks.

**Comment by pizzadude** [comment]
I have this issue too, Moto G 2014 running CM12.1

**Comment by theScrabi** [comment]
Please confirm if this still happens weith 0.7.4 or later !

**Comment by prashantchawla** [comment]
I think on 0.7.4 this happens only when the app fails to get video info page or related videos (expected). Otherwise it seems to be resolved. :)

**Comment by theScrabi** [comment]
Ok since you are supposed to use the latest version. I'll assume this is fixed.
