### ISSUE TITLE
To much empty space in landscape mode during preview

### ISSUE THREAD

**Issue by snelltheta** [theScrabi/NewPipe#18]
Screenshot says all.
![tmp_8604-screenshot_2015-09-14-20-35-221232023010](https://cloud.githubusercontent.com/assets/12014328/9867280/a3749dc4-5b20-11e5-97fd-0c1e5893be55.png)

**Comment by theScrabi** [comment]
Jep i know. I'll try to fix it :)

**Comment by theScrabi** [comment]
fixed
