### ISSUE TITLE
Starting with 0.7.4, opening links with external apps crashes the application.

### ISSUE THREAD

**Issue by syboxez** [theScrabi/NewPipe#180]
I use SpaRSS for all of my YouTube subscriptions, so I noticed this immediately after upgrading. Downgrading to 0.7.3 fixed this.

Also, where is the loading wheel? That seems to have gone with 0.7.4.

**Comment by Smultie** [comment]
Yeah, 0.7.4 is kind of a crash fest at the moment. Downloading, Audio only is also not working (Nexus 5X, stock, rooted, ElementalX latest)

**Comment by theScrabi** [comment]
Smultie: 0.7.4 was released from an unstable master branch, due to heavy code changes. I had to do this since youtube changed their website again, which rendered 0.7.3 partly unusable.

@syboxez: please provide the link.

**Comment by syboxez** [comment]
0.7.5 seems to have fixed the issue. I will do further testing, but for now, it seems fixed.
