### ISSUE TITLE
Higher quality mp3 downloads

### ISSUE THREAD

**Issue by santidavel** [theScrabi/NewPipe#184]
If there could be a way to download a higher quality mp3 version of the video it would be really great. Currently output is only 128kbps afaik. 320kbps would be a killer :)

**Comment by plumbe0** [comment]
YouTube supports max 192kbps audio so re-encoding to 320kbps would lower the audio quality even more.

**Comment by santidavel** [comment]
Oh, didn't now that.. Then nevermind. Hope youtube upgrades it's audio quality or stops compressing it so much

**Comment by theScrabi** [comment]
Since youtube changed their website again newpipe is not able to get the kpbs therefore filtering the best quality may not be working right now, which could be a reason. I'm working on it.
