### ISSUE TITLE
App crashes when trying to download

### ISSUE THREAD

**Issue by prashantchawla** [theScrabi/NewPipe#185]
Here's the log. 
[2016-02-16-01-48-09.txt](https://github.com/theScrabi/NewPipe/files/131397/2016-02-16-01-48-09.txt)

**Comment by algoprog** [comment]
I think the problem is in line 429:
02-16 01:48:20.706 W/System.err( 6016): org.json.JSONException: No value for dashmpd
Something related to MPEG-DASH support.

**Comment by theScrabi** [comment]
This seams like an error of 0.7.3 In 0.7.5 it will definitely be fixed.
