### ISSUE TITLE
foreground playing seems to block at 6.22

### ISSUE THREAD

**Issue by xiorcal** [theScrabi/NewPipe#188]
just watched 4 videos in a row which all blocked at 6 minutes 22 seconds. sliding a bit further un-block the player

**Comment by theScrabi** [comment]
https://github.com/theScrabi/NewPipe/issues/191

**Comment by xiorcal** [comment]
got that exact same bug on latest version.

**Comment by theScrabi** [comment]
Yes we still not have exoplayer.
