### ISSUE TITLE
Play/Pause button remains same in notification without changing.

### ISSUE THREAD

**Issue by vettukal** [theScrabi/NewPipe#189]
The backgroundPlayPause inside the player_notification does not change on click. Though music is getting paused and resumed as expected. 

Below is the screenshot I am attaching. It always stays as the play button for some reason. 
![playpausenotification](https://cloud.githubusercontent.com/assets/1246832/13084180/63db97f0-d4fe-11e5-9d04-7ec73396602b.jpg)

**Comment by theScrabi** [comment]
Thats an issue of android 4.4.4 and below. Will be fixed in 0.7.5.
