### ISSUE TITLE
Video doesn't load

### ISSUE THREAD

**Issue by amilopowers** [theScrabi/NewPipe#191]
I am using version 0.7.4 from f-droid. The video (720p) does load really fast until some point and doesn't continue then. Means I can watch like 1min of every video and then I've no chance to continue. Even when I reload and skip the first part it does the same with another minute or so.

**Comment by theScrabi** [comment]
I'm sorry this seams like a problem of the build in android mediaplayer. I'm looking forward to use exoplayer instead, so some of these issues may be gone then. But for now I can't help.
