### ISSUE TITLE
[0.7.4] Could not load video info page.

### ISSUE THREAD

**Issue by medeirosT** [theScrabi/NewPipe#196]
There are a few videos where I'm getting this notification.

Nothing happens then if I try to open this video in a browser, newpipe crashes.

Here's a screenshot:
![screenshot_20160219-101401](https://cloud.githubusercontent.com/assets/1336826/13179674/e5a11666-d6f2-11e5-9e10-d2493cf906df.png)

Here's the links to the videos:
https://www.youtube.com/watch?v=SZCvuGQCLvI
https://www.youtube.com/watch?v=-19Z_psHe7w

**Comment by theScrabi** [comment]
Yes. This will be fixed with 0.7.5.
