### ISSUE TITLE
Network error caused by long parsing error (screenshots) (fixed)

### ISSUE THREAD

**Issue by szafir1100** [theScrabi/NewPipe#198]
When I was trying to search for some videos, that what were happening on my screen:
[Screen](http://i.imgur.com/xHoo3R5.png)
Stacktrace from Android Monitor:
[Stacktrace](http://pastebin.com/ebkdhzLq)

Error was caused by spaces inside String viewCountInfo (YoutubeSearchEngine class), so Long.parseLong() couldn't handle that (i.e. 61 684 instead of 61684)
I've used regex to delete spaces and it works fine.
Phone model: HTC One M7
Android version: 5.0.2

[Fixed code screenshot](http://i.imgur.com/y0ZaKEU.png)

**Comment by theScrabi** [comment]
does it work now?

**Comment by szafir1100** [comment]
Yup, works fine now ;)
