### ISSUE TITLE
Video with likes disable won't load

### ISSUE THREAD

**Issue by isteba** [theScrabi/NewPipe#201]
Hi,

Thanks for this great application! I noticed a bug (maybe a feature but I don't think so :-)). It's seems like video with like/dislike disabled won't load. The following message appears but nothing happens next "could not get like count".

Examples:
https://www.youtube.com/watch?v=8S__mQH0bkQ
https://www.youtube.com/watch?v=Hqj29D5K83U

Version 0.7.4 from F-droid

**Comment by rrooij** [comment]
It is fixed in 0.7.5 as far as I know. I can't seem to reproduce the problem.

**Comment by theScrabi** [comment]
Yes a big feature of 0.7.5 is that NewPipe is finally able to handle missing information.
