### ISSUE TITLE
Include a Changelog Link, on the F-Droid Info' Page, 0.7.5.

### ISSUE THREAD

**Issue by locutis-of-borg-1999** [theScrabi/NewPipe#203]
Include a Changelog Link, on the F-Droid Info' Page.  None, as of 0.7.5.

**Comment by locutis-of-borg-1999** [comment]
Include a Changelog Link, within the F-Droid App', on Info' Page.  Not Present, as of: 0.7.5.

**Comment by rrooij** [comment]
We could simply link to the [releases page](https://github.com/theScrabi/NewPipe/releases).

**Comment by locutis-of-borg-1999** [comment]
Certainly.   It seems to suffice.  Some just link to text files.

https://f-droid.org/manual/html_node/Changelog.html#Changelog

**Comment by theScrabi** [comment]
Al right here:
https://gitlab.com/fdroid/fdroiddata/issues/404

(Funny fact. Not this is issue 404 xD)

**Comment by locutis-of-borg-1999** [comment]
I tell you what...  Now I'm looking for the girl who wears THIS SHIRT!!!!!:  http://champu.in/images/error-404-girls-t-shirt-india.png

**Comment by theScrabi** [comment]
xD yes please.

Also according to f-droid. This issue is fixed now.

**Comment by locutis-of-borg-1999** [comment]
:-)
