### ISSUE TITLE
"No stream player found, you may want to install one" error

### ISSUE THREAD

**Issue by jimmyrustles** [theScrabi/NewPipe#204]
NewPipe 0.4.1 has been giving me this error lately when I already have MX Player Pro installed, I was using NewPipe fine with MX Player for months previously, this has me stumped. When I hit install one, MX Player isn't even listed at all as a player, when it used to be previously.

**Comment by theScrabi** [comment]
Yea so the issue is that you still use 0.4.1. This is an outdated version. Please use the latest one.
