### ISSUE TITLE
Don't force orientantion

### ISSUE THREAD

**Issue by Magissia** [theScrabi/NewPipe#205]
The application should never force an orientation in any case. Currently, the application force portrait orientation in some cases.

**Comment by theScrabi** [comment]
If you put NewPipe in portrait mode, close it and reopen it, it will still be in portrait mode.

**Comment by theScrabi** [comment]
Oh I though you meant the player, but you most likely meant the UI right?
If so than this is a duplicate: https://github.com/theScrabi/NewPipe/issues/194
