### ISSUE TITLE
[feature request] 4.0.4 compatibility

### ISSUE THREAD

**Issue by pizzamaker** [theScrabi/NewPipe#21]
Please make it compatible with Android 4.0.4 :)

**Comment by theScrabi** [comment]
That could be harsh. A lot of functions are used witch require api level 16 (Android 4.1).

**Comment by theScrabi** [comment]
Ok minimum api level is 15 now. May cause some problems and Ui errors, but so far its working on 4.0.3.

**Comment by pizzamaker** [comment]
Thanks a lot!
