### ISSUE TITLE
Forever spinning wheel when trying to load video

### ISSUE THREAD

**Issue by tgp1994** [theScrabi/NewPipe#212]
Version 0.7.4, when trying to load videos linked to from reddit, they usually sit there forever with the spinning loading wheel and no other information about the video loaded. Here's a sample link: https://www.youtube.com/watch?v=j6cZ17sX1OA

**Comment by theScrabi** [comment]
Yes please update, with 0.7.5 it's working again.

**Comment by tgp1994** [comment]
When will it be on F-Droid? That's how I usually get my updates.

**Comment by theScrabi** [comment]
It is on f-droid. Update your database.

**Comment by tgp1994** [comment]
Strange, it should have been doing that automatically... I have it now though, thank you!
