### ISSUE TITLE
Trying to open a particular link gives "player config empty"

### ISSUE THREAD

**Issue by tgp1994** [theScrabi/NewPipe#215]
I noticed trying to open this particular link: https://youtu.be/dKa492JuLJ0 NewPipe sits at the spinning wheel, and shows a notification reading "player config empty". I'm fairly certain I'm using the latest version in F-Droid at this time.

**Comment by tgp1994** [comment]
Update: I just realized that the link goes to a removed video. Perhaps NP needs support to alert the user about removed videos?

**Comment by theScrabi** [comment]
I should. Therefore this can be considered a bug.

**Comment by theScrabi** [comment]
Seams like the latest version on the git master branch can handler this. However 0.7.6 can't.
