### ISSUE TITLE
failed to find pattern in https://youtu.be/yBjY6Aao6Ns?t=57s

### ISSUE THREAD

**Issue by tgp1994** [theScrabi/NewPipe#216]
Getting a "failed to find pattern in" error message when opening the link https://youtu.be/yBjY6Aao6Ns?t=57s although it appears to resolve just fine on YouTube.

**Comment by tgp1994** [comment]
Here's an additional link with the same problem: https://youtu.be/tw8TsxtWbiU?t=8s

**Comment by theScrabi** [comment]
Hm the links you sent seem to work, but the related/next videos fail.

**Comment by tgp1994** [comment]
You're right, I just tried it after opening the link in my browser first... Are you letting your browser resolve the link first i.e to https://www.youtube.com/watch?v=yBjY6Aao6Ns&feature=youtu.be&t=57s before you open it in the app? I'm trying to open the link (https://youtu.be/yBjY6Aao6Ns?t=57s) directly from the app, which doesn't work for me.

**Comment by theScrabi** [comment]
Than please provide a log, and tell me which version you use.

**Comment by tgp1994** [comment]
I'm not sure how to get the version number or log from NewPipe. According to F-Droid though, I have 0.7.6. Actually as an idea for a feature, it would be nice to be able to directly report bugs from the app with a log already attached.

**Comment by theScrabi** [comment]
I'm already ahead of you ;)
https://github.com/theScrabi/NewPipe/tree/advancedErrorHandling

A friend of mine is about to set up the ticket server right at the moment.

**Comment by tgp1994** [comment]
Excellent! I'd be happy to wait until the next release if you want. Thanks for all of your hard work on this app so far.

**Comment by theScrabi** [comment]
Seems fixed to me.
