### ISSUE TITLE
Search results displays wrong

### ISSUE THREAD

**Issue by CHRINIMUE** [theScrabi/NewPipe#217]
After searching in the landscape view and then switching in the Portrait view the search results will be shown false. Also when you are switching in the landscape view again.

Some Pictures:
![screenshot_2016-02-27-10-53-03](https://cloud.githubusercontent.com/assets/15434539/13372691/6e0d55c0-dd4f-11e5-8fb1-d496a095439e.png)
![screenshot_2016-02-27-10-51-22](https://cloud.githubusercontent.com/assets/15434539/13372693/6e13e2aa-dd4f-11e5-9f00-ce3e1b60201f.png)
![screenshot_2016-02-27-10-51-11](https://cloud.githubusercontent.com/assets/15434539/13372692/6e13c392-dd4f-11e5-91db-6f7489269c91.png)

**Comment by theScrabi** [comment]
what ? Which version are you using?

**Comment by CHRINIMUE** [comment]
I am using the the 0.7.6 Version.

**Comment by theScrabi** [comment]
Yes I could reproduce it, but I'm still not sure whats going on. The thumbnail width seems fixed size.

**Comment by roybaer** [comment]
It looks like the App is mixing list entries from portrait and landscape mode.

PS: That is not how you spell 'Search'!

**Comment by theScrabi** [comment]
Aw come on tha seartch could be weitten by me xD. I found it funny.

**Comment by CHRINIMUE** [comment]
Sorry, my english isn't very well. xD
But you understood what I am meaning. That is the important thing. :D

PS: Wie could write in german xD But then other people don't understand what we are writing and the gramatic and word spelling would be bad, too.

**Comment by theScrabi** [comment]
Ok i made a quick and dirty fix. The whole activity gets recreated after rotation, so this might solve this bug.
