### ISSUE TITLE
[0.7.6] Badly approximated number of views in the search results.

### ISSUE THREAD

**Issue by MoonfireSeco** [theScrabi/NewPipe#218]
NewPipe forgets the other digits of a video's number of views and it just shows the first digit:
In the search results, NewPipe says that a video has, like, 2-3 views. When I click the video it says that it has 2000-3000 views (and that's the true number).
Pic related, in the left we have a screenshot of the search results, in the right we have the true number of views each video has.
![next](https://cloud.githubusercontent.com/assets/17289219/13374232/1a7ae476-dd87-11e5-8938-3e544d99a0ea.png)

Running on Nexus 5 2013, Android 6.0 preview 3.

P.S: I was thinking that the problem might be that the app is not showing the K (for thousands of views) and M (for millions of views) in the Search Results, but NewPipe glitches even when the video has only hundreds of views. (Like in "Kewl MLP Video Collection").

**Comment by MoonfireSeco** [comment]
Have a more relevant example
![untitled](https://cloud.githubusercontent.com/assets/17289219/13374290/a5a64c38-dd88-11e5-82b2-7c8488619b06.png)

**Comment by theScrabi** [comment]
This failure is already fixed. Coming with the next version.
