### ISSUE TITLE
failed to find pattern inside of vnd.youtube:xxxxxx

### ISSUE THREAD

**Issue by malua** [theScrabi/NewPipe#229]
Hello, first of all thanks for the great app. 

I just noticed that if i open a trailer from "yatse", it opens newpipe but with this "vnd.youtube:xxx" command. i don't actually know if many apps use this, but it probably wouldn't be hard to just parse the youtube video id to a full address and play the video.

thanks again!

![image](https://cloud.githubusercontent.com/assets/7237428/13615456/ae5669ae-e575-11e5-9c4d-4500eef19da9.jpg)

**Comment by theScrabi** [comment]
Unless you give a link to the video I can only tell you to wait for the next version. As i see it the new version should accept vnd.youtube... urls.

**Comment by malua** [comment]
ok thats great. thanks for the answer. (i tried it with different videos so it probably doesnt depend on a specific video)

**Comment by theScrabi** [comment]
No its just that you can reach youtube videos via different urls. So far I didn't figure out all of them.
