### ISSUE TITLE
Video upload date in search results

### ISSUE THREAD

**Issue by epitron** [theScrabi/NewPipe#23]
I find that the upload date helps me frequently when trying to locate things like lectures by a person who gives a lot of talks. It would be nice if this was visible in the results.

Perhaps you could move the timestamp into the bottom-right-corner of the video thumbnail (similar to the youtube website) to save some space?

**Comment by theScrabi** [comment]
Nice. I had the same problem but from another perspective. I wanted to put the timestamp on top of the video thumbnail. But that i would have some empty space and I didn't know what to put there. Will come. When, I cant tell :/

**Comment by epitron** [comment]
LOL! Nice.

**Comment by theScrabi** [comment]
Thanks to darkon5 thats now part of the code :). Although i can not display the date itself, since youtube does not provide this. It only shows how long ago the video was uploaded.

**Comment by epitron** [comment]
That looks a lot better, thanks!
