### ISSUE TITLE
Player config empty error when opening link.

### ISSUE THREAD

**Issue by pypcz** [theScrabi/NewPipe#239]
https://www.youtube.com/watch?v=mDoLERQehXQ

**Comment by pypcz** [comment]
Screenshot.
![screenshot_20160313-124921](https://cloud.githubusercontent.com/assets/5565504/13728466/417b8bea-e91a-11e5-9633-f1a1df9ba7e9.png)

**Comment by pypcz** [comment]
So apparently this is caused by video being 18+. In that case a more descriptive error message would be helpful.

**Comment by theScrabi** [comment]
Will be fixed by the next version.
