### ISSUE TITLE
Easier-to-reach "play video" button

### ISSUE THREAD

**Issue by epitron** [theScrabi/NewPipe#24]
When I've got NewPipe configured to launch an external player, I have to stretch my thumb all the way up to the top-right corner of my phone to tap the play button. (I'm left-handed, so that button is super far away.)

Could you make it so touching the nice, big, friendly thumbnail plays the video? :)

**Comment by theScrabi** [comment]
:D yes i can do that :). I could also add some floating action buttons (i know that not all like those, so they would just be optional). Hm maybe I'll do both :)

**Comment by epitron** [comment]
Awesome! Thanks! :D

**Comment by theScrabi** [comment]
Ok for now i added the Floating Action Button, with a special option, to decide on witch side its displayed. The big tab on video thing is coming after.

**Comment by epitron** [comment]
Excellent. That works great.

Funnily, it's actually easier for me to hit when it's on the right side. I don't know if "Left-hand-friendly" is a good name for switching it to the other side. :)

**Comment by theScrabi** [comment]
Hm maybe I should just put the button in the middle.

**Comment by darkon5** [comment]
I'm working on a update for the video details screen. Also, the floating button appears too much to the middle on small screens, I already fixed that. (changed android:layout_margin="10pt" to android:layout_margin="10dp")

As soon I finish the layout I'll open a PR :)

**Comment by theScrabi** [comment]
ah thats cool thanks :)

**Comment by epitron** [comment]
Hmmm... I think being in the middle would get in the way. It's funny the way it is imo.

**Comment by theScrabi** [comment]
I set the layout in a way that you can scroll over that button. So you will be able to see all the content. Its similar to the android M AlarmClock.

**Comment by epitron** [comment]
After using it, I like it. Thanks! :)

**Comment by theScrabi** [comment]
Nice to hear :)

**Comment by epitron** [comment]
BTW, when I rotate the screen, it goes back to the old behavior of appearing on the left or right.. Is that for tablets or something?

**Comment by theScrabi** [comment]
Yea thats also meant for tablets. I think its than easier to reach with your thumbs.
