### ISSUE TITLE
WebM : Can't play video

### ISSUE THREAD

**Issue by Paviluf** [theScrabi/NewPipe#242]
By default the video is played in WebM (top left) but, at least for me, it fail. I have a message "Impossible de lire la video" in french (Can't play video). If I select MPEG-4 in the top left menu it work.

Is it a bug ? Is something needed in order to play WebM videos ?
Note that I don't have anything from Google installed.

Thanks !

**Comment by theScrabi** [comment]
No WebM is a free format. So it should be supported. But you need to give me some more information. What Video? Or does it happen with all. Also what android version do you use and what NewPipe version?

**Comment by Paviluf** [comment]
It seems to happen with all videos. I will do more tests.
I have a Motorola Razr i (intel x86) on CM 11. I use the NewPipe version from F-droid.

**Comment by Paviluf** [comment]
I downgraded my ROM (http://forum.xda-developers.com/razr-i/development/rom-unofficial-cyanogenmod-11-t2966855/page175) and now the WebM videos can be played but one in two the video is jerky.

**Comment by theScrabi** [comment]
xD There is only the f-droid version. I wanted to know the version number. How ever sounds to me like its not a problem related to NewPipe.

Try to donwload the WebM video, so you have it as a file. Now try to open it with your build in Player. Does that work?

**Comment by Paviluf** [comment]
I have the v. 0.7.6. 
I downloaded the WebM video with NewPipe (I hope it's the same, it have an webm extension) and I can read it with the build in Player. However if I use the built in player as an external player in NewPipe the video is jerky like with the NewPipe integrated player.

**Comment by theScrabi** [comment]
What means jerky? You mean it doesn't play that well or it just fails :/
However I can't help you. I'm no streaming expert, I only do crawling. However the new 0.7.7 is rolled out and should be available the next few days. It contains experimental exoPlayer support. So then try it with exoplayer, and tell me if that works :)

**Comment by Paviluf** [comment]
By jerky I mean chopped, there is stutter. The video is not smooth at all and somewhat hang for seconds.
I tested with VLC as an external player and it works !
I will try with the next version !

**Comment by Paviluf** [comment]
Hazou, the creator of the CM 11 ROM for the Razr i, [think that the problem can be in the ROM](http://forum.xda-developers.com/showpost.php?p=65843580&postcount=1748).

> I have the feeling that the Google video software decoders are slower than the ffmpeg (vlc also uses) the ROM provides. But because the Google's one are further up the line the ffmpeg doesn't get called.

**Comment by theScrabi** [comment]
Hm may be. Google itself says that their mediaplayer may not be the best.

**Comment by Paviluf** [comment]
Hazou [found](http://forum.xda-developers.com/showpost.php?p=65871591&postcount=1753) a fix for the ROM ! So it's not a Newpipe problem and I can close this issue.
I still not have tested 0.7.7, the fdroid repo is still on 0.7.6.
Thanks !

**Comment by Paviluf** [comment]
I saw on the Fdroid website that Newpipe is at 0.7.7 but I can't update to it. Fdroid with updated repo on my phone have only 0.7.6 is it normal ?

**Comment by theScrabi** [comment]
Meh I see that f-droid morns on that g*** d*** commons-lang lib again -.- maybe this could cause that on some devices its not visible :(

**Comment by Paviluf** [comment]
Perhaps, my phone is a x86. Some other people are also affected by the "broken" version 0.7.7 from fdroid. Do you think you can make them fix the app ?

https://f-droid.org/forums/topic/f-droid-not-showing-updated-app-after-repo-update/
https://github.com/theScrabi/NewPipe/issues/244

**Comment by Paviluf** [comment]
The 0.7.8 is available on Fdroid and I can install it on my phone. Thanks !
I have tested exoplayer and it work great. Something that can be improved is the top bar that doesn't disappear.

**Comment by Paviluf** [comment]
May I ask why you reopened the issue ?

**Comment by theScrabi** [comment]
Excelent question. I'd say due to a layer 8 error.
