### ISSUE TITLE
[0.7.6] Downloadfolder cannot be changed

### ISSUE THREAD

**Issue by hodor22** [theScrabi/NewPipe#243]
If I change Download folder to something else , the app is not changing anything in the background and puts everything in the default download folder

**Comment by theScrabi** [comment]
What should I say, downloading is still a bit hacky. Needs to be re factored anyway.

**Comment by satiricon** [comment]
I was thinking that maybe I could use GigaGet code's to add a better downloading to NewPipe.

https://github.com/PaperAirplane-Dev-Team/GigaGet/tree/master/app/src/main/java/us/shandian/giga/get

What do you think? I could give it a try.

**Comment by theScrabi** [comment]
I think, that I already had the same idea. I just didn't have the time to do implement that. So yes please :)

**Comment by satiricon** [comment]
Ok. I'll try making something rough first just to see how it could work.

**Comment by satiricon** [comment]
I have something working. I still need to do lots of cleanup, make GG's code use NewPipe's settings and stuff but it's already working.

![screenshot_2016-04-21-19-00-27](https://cloud.githubusercontent.com/assets/425749/14725716/0d0f528a-07f4-11e6-8e69-00b8af92e45b.png)
This dialog might not be necessary but I can probably add the video or audio selector to it.

![screenshot_2016-04-21-19-00-49](https://cloud.githubusercontent.com/assets/425749/14725718/0d1906e0-07f4-11e6-9eac-95cc6374e145.png)

![screenshot_2016-04-21-19-01-01](https://cloud.githubusercontent.com/assets/425749/14725717/0d15ed98-07f4-11e6-9892-a525d08e1f7b.png)
Works like expected when pressed.

**Comment by satiricon** [comment]
This is how I'm rebuilding DownloadDialog. As the user will have the option to download both video and audio, the file extensions will be added to the file name before they're added to the download queue. 

I'll be done in 2/3 days.

![screenshot_2016-04-28-13-15-54](https://cloud.githubusercontent.com/assets/425749/14893054/29abf63c-0d44-11e6-8fed-10763e8a8b61.png)

**Comment by satiricon** [comment]
#285
