### ISSUE TITLE
0.7.7 contains broken native code

### ISSUE THREAD

**Issue by mvdan** [theScrabi/NewPipe#244]
So 0.7.7 built fine on F-Droid, but the apk is broken. If you do `aapt dump badging file.apk`...

```
[...]
native-code: 'commons-lang-2.6.jar'
```

This does not happen with 0.7.6. If you do `apktool d file.apk` you'll see `lib/commons-lang-2.6.jar`, which is causing this issue. That folder is for arch-dependant binaries, such as `lib/x86/...`.

**Comment by theScrabi** [comment]
Ok I removed commons-lang completely. Should be fixed by the next build.

**Comment by tgp1994** [comment]
Thanks, looking forward to seeing it soon in the F-Droid repo!
