### ISSUE TITLE
Filename:  use " " insteand of "_"

### ISSUE THREAD

**Issue by hydroid7** [theScrabi/NewPipe#246]
If you download files, there are _ instead of spaces. Can we change it?

**Comment by theScrabi** [comment]
At the moment I can't tell what's exactly going on. The whole download thing is still some kind of hack, and nothing final. When I do the redactor, I'll keep that issue in mind.

**Comment by hydroid7** [comment]
At first:  Okay i get your point. 
I've just check the code and in file DownloadDialog.java there is a method to normalise filenames. May you could add `nameToTest.replaceAll("_"," "); ` after line 140?

Since I'm using a Linux Distro, i cannot even compile any Android App. -.-  Thatsway i'm not able to test anything.

**Comment by wb9688** [comment]
This problem is caused by the following lines in DownloadDialog.java:

```java
    /**

* #143 #44 #42 #22: make shure that the filename does not contain illegal
chars.

* This should fix some of the "cannot download" problems.

* */

    private String createFileName(String fName) {

        // from
http://eng-przemelek.blogspot.de/2009/07/how-to-create-valid-file-name.html

        List<String> forbiddenCharsPatterns = new ArrayList<> ();

        forbiddenCharsPatterns.add("[:]+"); // Mac OS, but it looks that
also Windows XP

        forbiddenCharsPatterns.add("[\\*\"/\\\\\\[\\]\\:\\;\\|\\=\\,]+");
// Windows

        forbiddenCharsPatterns.add("[^\\w\\d\\.]+"); // last chance... only
latin letters and digits

        String nameToTest = fName;

        for (String pattern : forbiddenCharsPatterns) {

            nameToTest = nameToTest.replaceAll(pattern, "_");

        }

        return nameToTest;

    }
```

So, apparently that was added to make sure it doesn't contain illegal
characters...

**Comment by hydroid7** [comment]
I see the Problem. It is a solution to replace all occurrences of _ with space? Spaces are allowed in any op System.

**Comment by wb9688** [comment]
@hybroid07 so you want `nameToTest = nameToTest.replaceAll(pattern, " ");`
instead of `nameToTest = nameToTest.replaceAll(pattern, "_");`?

**Comment by hydroid7** [comment]
No, i suggested to add this line after all "bad" Chars are escaped. That
means to add it before the return Statement.
Am 21.03.2016 15:14 schrieb "wb9688" <notifications@github.com>:

**Comment by hydroid7** [comment]
@wb9688 Oh sorry, I think I didn't read your comment carefully. 
Yes this is exactly what I would suppose!

**Comment by theScrabi** [comment]
This discusion might be obsolet, since we replaced the download code by gigaget.

**Comment by satiricon** [comment]
@theScrabi I think we are still using the same namjng pattern (with the _) or you changed it? I know I didn't.
