### ISSUE TITLE
Show share sooner than download

### ISSUE THREAD

**Issue by PanderMusubi** [theScrabi/NewPipe#257]
On my smartphone in portrait mode the share icon is not shown, but it is shown in landscape. The download icon is always shared. However, the download button on a smartphone is use much less than the share button. Could in portrait mode the share be shown instead of the download icon?

If you do not want to make this a default behaviour, could you offer it as an option for peope who share more than download?

**Comment by theScrabi** [comment]
Actually no. Downloading is one of the big features of NewPipe, and I want users to realize that. To be honest, writing code to make the share button have ha higher priority is in my opinion not worth the work. But if you like, you can always contribute code to NewPipe.

**Comment by PanderMusubi** [comment]
OK, I understand. Before creating an issue for it, would you support a menu when pressing the menu button while playing a video and offering Share and other menu items there too?

**Comment by theScrabi** [comment]
Yes that could be done.

**Comment by PanderMusubi** [comment]
Do you need a new issue fo this?
