### ISSUE TITLE
Need a few attempt to make work external player (VLC)

### ISSUE THREAD

**Issue by Paviluf** [theScrabi/NewPipe#263]
I need a few attempt to make external player (VLC) play a video. The first time it can't play the video (VLC display "erreur de lecture", in english "playback error"). Often the second time it work but sometimes it need more than 2 attempts to work like in the logcat I linked that needed 3 attempts.

**Comment by Paviluf** [comment]
I noticed that sometimes that work directly on the first try.

**Comment by theScrabi** [comment]
What version are you using?

**Comment by Paviluf** [comment]
NewPipe 0.7.8
VLC 1.9.0

**Comment by Paviluf** [comment]
@theScrabi did you found something ?

**Comment by theScrabi** [comment]
Sorry don't have time at the moment.

**Comment by Paviluf** [comment]
Did you found some time ?

**Comment by Paviluf** [comment]
It seems that is a VLC problem. I used VLC 1.9.0 from F-droid but with VLC 1.7.5 the problem is not here. It seems that VLC 1.9.0 is not an official version.

https://trac.videolan.org/vlc/ticket/17037#ticket
