### ISSUE TITLE
New welcome screen design

### ISSUE THREAD

**Issue by ponypower** [theScrabi/NewPipe#265]
The current welcome screen lacks of cool design. See the attached image how it should look like in my opinion. Tapping anywhere on the surface would activate the search bar. (The original search icon is missing from this image, but would be part of the design.)

![newpipe design](https://cloud.githubusercontent.com/assets/16841860/14407178/a6a990a6-febf-11e5-8a73-f6a0f4a4bedd.png)

I dont have the tools nor the experience to code for android so tell me what details you need to put this design into the app.

**Comment by theScrabi** [comment]
Hey nice one, but don't focus on the welcome screen to much, I already plan to replace it with trending videos.

I see you are good with graphics. So there are several things you can do first you could try to redesign our website [newpipe.schabi.org](https://newpipe.schabi.org). Second, I want a new design for the video player, but I don't know how it should look like. If you like you could create and send me some suggestions.
