### ISSUE TITLE
Sleep timer

### ISSUE THREAD

**Issue by pachacamac** [theScrabi/NewPipe#27]
It's super awesome that this app keeps playing even when the display is off. Now If it had a sleep timer (stop playback after x minutes) this would be really cool.

**Comment by theScrabi** [comment]
Lol. I'll keep that in mind.

**Comment by theScrabi** [comment]
But i think when i add the Audio option this will be obsolete, isn't it?

**Comment by pachacamac** [comment]
What is the Audio option?

**Comment by theScrabi** [comment]
It is the option to only play the audio stream of a video. Which now is implemented.

**Comment by DamageIncorporated** [comment]
I also miss a sleep timer. My wife tends to listen to eight hour audio books at night, so when I wake up, I have to stop playback manually. 
A sleep timer would be really handy here :-)

**Comment by PNeigel** [comment]
Just chiming in to say a sleep timer would be awesome! Is this still on the ToDo list?

**Comment by hightbross** [comment]
It would be an excellent addition!

**Comment by johannesrave** [comment]
++

**Comment by Towelie90** [comment]
I think a sleep timer is most important feature that is still missing. Is there a reason why it is still missing?

**Comment by Bauxitedev** [comment]
Why is this issue closed? I'd love to have this. VLC has a sleep timer but I prefer NewPipe.

**Comment by theintel** [comment]
So this feature didn't get added even after 9 years. Why?
