### ISSUE TITLE
Choose download directory with dialog or intent

### ISSUE THREAD

**Issue by EdoPut** [theScrabi/NewPipe#284]
request: Enhancement

What should happen:
The app will let you choose the download directory using a touch interface, a dialog or an intent.

What happen:
You can edit a path that points to the directory

This is somewhat easy and should be a good enhancement, due to android's paths it's not that simple for users to choose another directory, like on the external sd, to be the target dowload folder

**Comment by satiricon** [comment]
This was done in #314.
