### ISSUE TITLE
Feature Request: Newpipe as share target

### ISSUE THREAD

**Issue by gdevenyi** [theScrabi/NewPipe#288]
As a quick improvement to the UI of NewPipe, it would be great if it supported being a target of sharing. This way, I could navigate youtube using the native app, and then share to newpipe to play the video I want.

**Comment by 42SK** [comment]
I believe this is a duplicate of issues #84 and #101.
There's an external app that allows you to open videos in NewPipe via the share menu:
https://github.com/theScrabi/ShareWithNewPipe

**Comment by gdevenyi** [comment]
That works.
