### ISSUE TITLE
Why don't create the ultimate YouTube addon than Firefox mobile need instead of create a full YouTube app which will be very little use. 

### ISSUE THREAD

**Issue by LifeIsStrange** [theScrabi/NewPipe#29]
Actually, YouTube on Firefox for Android is a hell, Firefox can't play YouTube properly without the addon enable YouTube mobile player (which simulate the Chrome useragent), Firefox can't select and select by default the resolution (It's always 360p..), Firefox can't select the speed of the vidéos, it can't share à video and create playlist and it can't select subtiles, Firefox also need a stylish which rework all the YouTube mobile design and it need the ability to disable the play in background with a setting. 
And THE Firefox big lack is that there is No addon for download videos !! 
If you create an addon which merge all theses essentials features, it will be a revolution ! 
Actually I don't know code but I will learn the JavaScript for actively help you if it's not too dificult. 
Also sorry for my bad english.

**Comment by darkon5** [comment]
Working on Android is way more powerful than working as a Firefox extension.

NewPipe is a standalone app for watching Youtube videos without the Google API.

**Comment by LifeIsStrange** [comment]
You have probably reason but your awesome and free app will be use by very little person, it's a fact.  An addon can touch a very more large public. Also I think that use a specific app for a website is a regression, it's not unified with the browser. Personnaly I dream of a decent YouTube in my Firefox Android and I am probably not the only one. 
Why not do the two ? Create an addon and create an powerfull app ? I think that many code can be share. And the addon could do ad for your app and everybody is happy :)

**Comment by darkon5** [comment]
I think that doesn't work like that. Anyway, let's see what the original dev has to say :)

**Comment by epitron** [comment]
Can you configure Firefox to launch external apps when clicking links? If so, then Firefox could just hand off youtube urls to NewPipe! :)

**Comment by theScrabi** [comment]
@darkon5 I say: @LifeIsStrange JavaScript is slow, and firefox addons don't feel very native. The intetion of this app was to get away from firefox and have a native youtube frontend, with a native player. Therefore I wanted to have a free (as in libre) youtube player that does not use the G api. I didn't want to create something big or something that should replace everything. I just wanted to watch some youtube.

@epitron: Cool idea.
Although there is a workaround: Touch the link until a menu pops up. There you can choose to open it with NewPipe. But thats not very nice.

@LifeIsStrange: To learn programming is never a bad idea.  It enables you to create someting others couldn't do the way you want it to be. So if you think a frefox addon would be a great thing, than just do it :). Although id rather like to sea an implementation of epitrons idea ;).
