### ISSUE TITLE
Suggestions are not displayed anymore

### ISSUE THREAD

**Issue by theScrabi** [theScrabi/NewPipe#292]
Hi,

I noticed that Suggestions are not displayed any more. I just don't have time to fix it. May someone help?

mfg schabi

![screenshot_2016-05-09-14-01-44](https://cloud.githubusercontent.com/assets/1891273/15113922/6c63b3f0-15f7-11e6-937a-b69b82cb1fa8.png)

**Comment by theScrabi** [comment]
OK... :(

**Comment by theScrabi** [comment]
I realy need to get back to working on NewPipe :/

**Comment by satiricon** [comment]
@theScrabi If you are out of time you could give some contributors permissions to help with the development. I can volunteer to help with the project if you want.

**Comment by prashantkhurana** [comment]
@theScrabi  can you tell me how to reproduce the issue? I might be able to take a look at it. It is working for me. I tried for the very same video.

**Comment by theScrabi** [comment]
I didn't figure it out yet. It happes with all vids.
