### ISSUE TITLE
Regex exception with youtu.be link

### ISSUE THREAD

**Issue by Nono-m0le** [theScrabi/NewPipe#293]
From time to time, when I clic on a video link, then want to see a suggestion, I got the error : failed to find pattern "youtu\.be/([a-zA-Z0-9_-]{11}) inside of https://youtu.be/watch?v=xxxxxx" 

The 'watch?v=' seems to be missing on the regex.

**Comment by theScrabi** [comment]
watch?v= is new. Never saw a youtu.ve link having jat before.

**Comment by Nono-m0le** [comment]
Not that new. 6+ years. ( cf: http://www.presse-citron.net/raccourcisseurs-durl-youtube-devient-un-site-belge/)

**Comment by theScrabi** [comment]
Hm...

**Comment by Nono-m0le** [comment]
need help for the regex ?

**Comment by theScrabi** [comment]
If you like you can submit a pull request.

**Comment by satiricon** [comment]
This urls are working fine now.
