### ISSUE TITLE
Error: Could not decrypt video url signature.

### ISSUE THREAD

**Issue by tgp1994** [theScrabi/NewPipe#299]
I've noticed starting today that Newpipe cannot load any video URLs (I'm loading them from reddit). When it opens, it will attempt to load the video for a second, then a popup says "Could not decrypt video url signature." and the video fails to load or play. Possibly a Youtube backend change?

**Comment by locutis-of-borg-1999** [comment]
Same here.  

NewPipe shows, "Could not decrypt video url signature.", and never loads videos, only search results.


{
   "user_action": "user report",
   "exceptions": [],
   "os": "Linux Android 4.1.2 - 16",
   "time": "2016-05-24 22:23",
   "ip_range": "108.117.0.0",
   "request": "user_report",
   "service": "Youtube",
   "content_language": "en",
   "user_comment": "NewPipe shows, \"Could not decrypt video url signature.\", and never loads videos, only search results. ",
   "version": "0.7.8"
}

**Comment by satiricon** [comment]
This is a duplicate of #298. It's already fixed.

**Comment by tgp1994** [comment]
Oh, I was wondering about that issue. AFAICT, they never mentioned the error message that pops up so I assumed it was for a different thing. I hope the update will be on F-Droid soon!

**Comment by locutis-of-borg-1999** [comment]
I use F-Droid, as well.  Dev'(s) are quite proactive, and consider users, especially compared to others.  It's probably in the pipeline.  My F-Droid install polls the repo's daily, so I'm certain to see the patched versuon, relatively soon.  

Thanks again, for a great app' that works well, while a "work-in-progress".  And, let's not forget that the forces behind Youtube, Google, Facebook, et cetera, are NOT the best allies, or bedfellows.  But, they've got the subscribers, and content.  :|

**Comment by BedHead911** [comment]
It works again... But I never updated newpipe... Did youtube change it back?

**Comment by tgp1994** [comment]
@BedHead911 Yeah, I just noticed this too. Must have been a change Youtube reverted. I was not expecting to be using NewPipe this quickly again, I'm pleasantly surprised!

**Comment by theScrabi** [comment]
I didn't even notice any issue.

**Comment by nrchycheng** [comment]
Tube Mp3 downloader.
How do I fix this?

**Comment by theScrabi** [comment]
You don't Tube Mp3 downloader is an unofficial Illegal fork. Use NewPipe.
