### ISSUE TITLE
Where is the rotate button

### ISSUE THREAD

**Issue by rudi123** [theScrabi/NewPipe#313]
... when watching a video in fullscreen mode? It was such a nice feature to manually adjust the screen orientation. Is their a chance to get this feature back? 

Like your app very much. 

Regards Rudi

**Comment by wb9688** [comment]
It's still there, unless you've enabled ExoPlayer in the settings…

**Comment by rudi123** [comment]
I see. Thank you!

**Comment by theScrabi** [comment]
I think it's about time to ditch that default mediaplayer, and give exoplayer the other ui...
