### ISSUE TITLE
Signing in to Youtube

### ISSUE THREAD

**Issue by Aevann** [theScrabi/NewPipe#329]
Can this be added ?

**Comment by theScrabi** [comment]
No.

**Comment by theScrabi** [comment]
Sorry but this is deffinetly not what NewPipe was designed for.

**Comment by halcion** [comment]
Why the hell not. Seems like a logical request, how else are we supposed to retrieve our YouTube history, like and dislike videos. NewPipe, damn such a promising frontend. So close yet so far.

**Comment by halcion** [comment]
Why the hell not. Seems like a logical request, how else are we supposed to retrieve our YouTube history, like and dislike videos from NewPipe, oh wait, you can't. It's a YouTube frontend isn't it, and you give no satisfactory reason for not implementing that. Just a cryptic and vague not what it's meant for nonsensical reply. Being a frontend on that merit alone is very much in the realm of and not only what it should be capable of but meant for as well. NewPipe, damn such a promising frontend. So close yet so far.
