### ISSUE TITLE
Next video in a sequence not in the suggested list

### ISSUE THREAD

**Issue by FrancisMurillo** [theScrabi/NewPipe#332]
version: 0.8.0

Say I'm playing a let's play video series and I want to move on to the next video, sadly the next video is the series in nowhere to be found. I can find it by going two videos forward then selecting the video before it. Kinda like +2 - 1.

I believe this is a usability issue, it's more of an annoyance to go forward then back just to go forward. 

Great app by the way.

**Comment by theScrabi** [comment]
I have no influence in the order how videos appear. Its just shown like youtube would display it.
Also if you are talking about playlists, they are currently not supported.

**Comment by FrancisMurillo** [comment]
Oh okay, I thought it would be a index issue. Thanks for responding.
