### ISSUE TITLE
Downloaded files invisible to Linux

### ISSUE THREAD

**Issue by n8chz** [theScrabi/NewPipe#334]
They show up in file manager apps on Android, but when Android Lollipop device is mounted on Linux system, all files in a directory except those downloaded by NewPipe show up (using nemo, ls, others).

**Comment by icasdri** [comment]
This could be a caching issue on the MTP device (meaning the MTP interface has not caught up with recent filesystem changes). Have you tried rebooting the device, reconnecting, and trying again? Or, have you tried pulling the files/directory from `adb`?

**Comment by theScrabi** [comment]
I also don't think it has something to do with NewPipe. It produces files as any other app would do.
