### ISSUE TITLE
Nullpointer while searching

### ISSUE THREAD

**Issue by motatuc** [theScrabi/NewPipe#353]
Hello

I did search for some music and newpipe crashed. find the log below.

>{
"user_action": "searched",
"request": "randomsearch",
"content_language": "en",
"service": "Youtube",
"version": "0.8.0",
"os": "Linux Android 6.0.1 - 23",
"time": "2016-08-27 12:34",
"ip_range": "17X.0.0.0",
"exceptions": [
"java.lang.NullPointerException: Attempt to invoke virtual method 'org.jsoup.select.Elements org.jsoup.nodes.Element.children()' on a null object reference\n\tat org.schabi.newpipe.extractor.services.youtube.YoutubeSearchEngine.search(YoutubeSearchEngine.java:94)\n\tat org.schabi.newpipe.extractor.SearchResult.getSearchResult(SearchResult.java:32)\n\tat org.schabi.newpipe.VideoItemListFragment$SearchRunnable.run(VideoItemListFragment.java:111)\n\tat java.lang.Thread.run(Thread.java:818)\n"
],
"user_comment": ""
}

**Comment by theScrabi** [comment]
Please send the log to our bug system via mail.
