### ISSUE TITLE
Show Android icon to open NewPipe from the Address Bar in Firefox Mobile

### ISSUE THREAD

**Issue by newluck77** [theScrabi/NewPipe#37]
Hi everybody,

I hope this is no duplicate. I was wondering if the method of opening NewPipe from the address bar can be implemented, the same way as it works for e.g. the Wikipedia app:

![img_20150922_125251](https://cloud.githubusercontent.com/assets/8948865/10016651/d84f5c1a-6128-11e5-9482-08e06db18595.JPG)

**Comment by theScrabi** [comment]
I don't know the mechanism behind that. How ever, NewPipe can catch action.VIEW . But this seams to be something different.

**Comment by newluck77** [comment]
It seems to work now. A click on the Android icon opens NewPipe! :+1: 

![img_20151005_120232](https://cloud.githubusercontent.com/assets/8948865/10277840/30453e5a-6b59-11e5-82a2-4d7735f8d869.JPG)

**Comment by newluck77** [comment]
Wait a minute... I cheered to early: it only works the first time. On every following video, NewPipe plays the very first video again.

An example: I press the Android icon on Video A and NewPipe opens. I go to Video B, press the icon and NewPipe opens, but plays Video A again.

**Comment by theScrabi** [comment]
Does it also show the meta informations about video a when opening video b, or is it just the stream that does not fit?

**Comment by newluck77** [comment]
I cannot make it work now at all. NewPipe opens, when I click the 
Android icon, but it does not load the video (there is only the grey 
turning circle)...

**Comment by theScrabi** [comment]
Hm probably the loading thread crashes. Can you please give a log, then we'll see :).

**Comment by theScrabi** [comment]
Seems this error was related to this issue here:
https://github.com/theScrabi/NewPipe/issues/50

Should be fixed by now.

**Comment by newluck77** [comment]
Oh, sorry, I did not see that you had responded. Glad that it got solved!
