### ISSUE TITLE
External player

### ISSUE THREAD

**Issue by JasperWeiss** [theScrabi/NewPipe#41]
When using vlc media player it shows the url as the name. Is there any way you could make it show the name of the video instead? If so, you might also be able to change 'unknown artist' to the name of the channel.

Also, thanks for making this app! You're awesome

**Comment by epitron** [comment]
I just submitted a pull request for this: #43 

You can try building my fork if you want to test it out: https://github.com/epitron/NewPipe

**Comment by JasperWeiss** [comment]
@epitron Great, I'll check it out. Thanks!
