### ISSUE TITLE
Cannot play audio m4a audio stream

### ISSUE THREAD

**Issue by dalb8** [theScrabi/NewPipe#46]
I tested on Nexus S with CM 11. Cannot play audio streams; dialogue asks me to install org.videolan.vlc but I have it installed. If I set audio format to webm and restart the app the VLC for Android opens as expected.

I tested on Nexus 7 with CM12.1. Dialog appeared telling me to install VLC once but I tried again and all streams play. Left format at m4a this time.

**Comment by theScrabi** [comment]
Yes i noticed that. Next release will fix that.

**Comment by theScrabi** [comment]
Hm well I don't know. I couldn't reproduce the error, but i enabled stack tracing at the point where it happens. So if something goes wrong again please send me a log file catlog file.
