### ISSUE TITLE
add chromecast support

### ISSUE THREAD

**Issue by tspacepilot** [theScrabi/NewPipe#47]
With chromecast support, this app will do everything I need it to

**Comment by theScrabi** [comment]
Is chrome cast suppoert working with free software/libraries?

**Comment by theScrabi** [comment]
https://github.com/theScrabi/NewPipe/issues/105

**Comment by pizzadude** [comment]
I know this is an old issue, but just in case anyone's interested, you can share a video from NewPipe to an application like BubbleUPNP or Allcast and it will work with the chromecast. But that's only if you're okay with installing proprietary apps..

**Comment by KeizerDev** [comment]
@tspacepilot @pizzadude Fixed in #351 ;)

**Comment by KeizerDev** [comment]
@theScrabi let's implement this https://github.com/DroidsOnRoids/Casty
