### ISSUE TITLE
New icon

### ISSUE THREAD

**Issue by halcyonest** [theScrabi/NewPipe#49]
While NewPipe app interface follows Material Design, its icon doesn't and seems NewPipe needs a new icon. I'm not a designer, just suggesting an idea so I quickly made a sample icon below. Also when you launch NewPipe app, big ugly playback symbol appears on the screen. Instead NewPipe needs a new modern logo or NewPipe can just simply display the list of recommended videos just like YouTube app. I highly recommend the second one.

![icon](https://cloud.githubusercontent.com/assets/12594372/10389724/c34430f0-6eae-11e5-93b5-61ddaf1db50f.png)

*Download ![icon.svg.png](https://cloud.githubusercontent.com/assets/12594372/10389723/c3441b42-6eae-11e5-88ef-c4ef5b8d0266.png) and change '.png' extension into '.svg' to get an original SVG file.*

**Comment by theScrabi** [comment]
Well since I am just a programmer, I only care much about the actual working of the program. I'd appreciate if someone else would care about the design. So this first attempt is already pretty god. Keep it going :)

**Comment by theScrabi** [comment]
So how is icon designing going on? I'm about to release the next version in the next few days.

**Comment by theScrabi** [comment]
Ok i now added, and slightly modified your icon according to this design guide: https://www.google.com/design/spec/style/icons.html#icons-product-icons
But i might have messed it up. It feels so incomplete :P. But i'm not a designer :/
