### ISSUE TITLE
Fix for Youtube mobile links

### ISSUE THREAD

**Issue by sirpicklesiv** [theScrabi/NewPipe#50]
From Firefox Mobile, currently NewPipe will only work with links that look like this:
https://m.youtube.com/watch?v=1234567
It however will not work with links that look like this:
https://m.youtube.com/#/watch?v=1234567
https://m.youtube.com/?#/watch?v=1234567

**Comment by Natureshadow** [comment]
Reproduced it.

Fixing the handler would be great!

**Comment by theScrabi** [comment]
Yes thats true there is no filter for /#/ or /?#/ links. Thanks for noticing. I will add it in the next version.

**Comment by theScrabi** [comment]
All right should be fixed for now.
