### ISSUE TITLE
Full landscape rotation

### ISSUE THREAD

**Issue by dugite-code** [theScrabi/NewPipe#52]
Currently rotation to landscape seams to only work one way, so when I'm at my desk with my charger plugged in the video is locked upside down.

It would be great if the rotation could be enabled for both ways of holding the phone.

**Comment by theScrabi** [comment]
Hm on my phone its working.

Bu since it has been a while since i changed something on my code, i can't remember if i am running a self made, or the fdroid version on my smartphone. 

If im running selfmade, than it will probably come with the next version :)

**Comment by theScrabi** [comment]
Ok i broke the last release. Therefore the changes on the rotation thing where ned presend in the f-droid version. As i said the next realease will fix it. (Unless i'm to stupid to change the version code again)-
