### ISSUE TITLE
Lack of Time

### ISSUE THREAD

**Issue by theScrabi** [theScrabi/NewPipe#58]
Hallo,

as you might have noticed, in the past three weeks i was not able to upload any new version of NewPipe. Thats because i currently have some other projects going on, and in addition to that i have less time than three weeks before. Therefore if we want to get on with NP id need some help. So if you know java and/or android, and you don't know where to waste your spare time at, help improve newpipe. It already helps when i get layout files, like some of you already contributed.

So if you want to help, please tell me.

:)

**Comment by darkon5** [comment]
As you already know, the only help I can give right now it's updating the layout files and designing a webpage that barely can work. I'm a Java student right now, but I think I'll need some time to be able to actually be able to do something. Coding right now I would be more of a slow-down than a help.

I really like this program and I'm genuinely interested on it. It's also a great opportunity to learn, so count me in in whatever I can be helpful =D

**Comment by theScrabi** [comment]
Well that's the nice thing about git. Two ore more can work on the same project, and as long as they are not working on exactly the same problem, the probability that they are crashing is pretty low.
I'm about to gather all thinks which need to be done next. So than you can choose what you would like to do.

**Comment by medavox** [comment]
I'd like to help. What's the build environment/toolset?
It's been a while since I did anything specifically for Android (2013 I think?), but I work in Java all the time.

**Comment by theScrabi** [comment]
I'm using regular Android Studio, with regular android sdk, and the current gradly. So nothing exotic.

**Comment by narutosanjiv** [comment]
What kind of help you needing?.

**Comment by LifeIsStrange** [comment]
I can only do tests on my phone,report bugs and thinking on how improve the app. But I don't know code. 
Maybe I can translate the app in french.

**Comment by meidei** [comment]
I will do my best to spread the word and motivate people to contribute (I can't code myself). I'm really happy to see a free-software alternative to Youtube's non-free mobile and web interface.

**Comment by shekhar12020** [comment]
Sure, I'd like to help & contribute for New Pipe. :-)

**Comment by 9662** [comment]
Hi! I don't do Java, but as an idea, if you could identity (or create) any open issues that you think would be particularly accessible to someone unfamiliar with your code base, and tag them as "help wanted", with perhaps a little note on how you'd envisage tackling the problem or difficulties you foresee, that might encourage volunteers to jump in?

In any case, thanks a lot for your effort!

**Comment by theScrabi** [comment]
@9662 That is a good idea. Generally the CommintFeatures section in the readme says already what needs to be none. But you are right, with issues it is much clearer.

**Comment by theScrabi** [comment]
Ok I think this issue can be considered close. But that does not mean help is not welcome anymore. Help is ALWAYS welcome :)
