### ISSUE TITLE
[Feature request] Support for timestamped links

### ISSUE THREAD

**Issue by utack** [theScrabi/NewPipe#59]
Youtube allows links with timestamp, such as
https://www.youtube.com/watch?v=-ABcdefGhij#t=2m15s
(Intentionally broken video ID above, no advertisement intended)
Links work fine, but additional support to parse the timestamp and seek accordingly would be great

**Comment by theScrabi** [comment]
Ok. I'll keep that in mind.

**Comment by medavox** [comment]
This has now been implemented in the branch 'refactoring'; it currently needs a code review before merging into master.

**Comment by utack** [comment]
Works perfectly, thank you

**Comment by theScrabi** [comment]
Is that part of the current version? @medavox I didn't notice you did that xD.

**Comment by utack** [comment]
0.6.1 off F-Droid

**Comment by theScrabi** [comment]
Ah good. I didn't know that is already implemented. @medavox thanks :)

**Comment by medavox** [comment]
No problem :)
