### ISSUE TITLE
Update versioncode to reflect

### ISSUE THREAD

**Issue by krt16s** [theScrabi/NewPipe#60]
0.4.2 is tagged, but version and versioncode in build.gradle are still at 0.4.1 (4).

**Comment by darkon5** [comment]
If you could check the version from Settings, maybe a "About" section... I think that would be cool too =D

**Comment by theScrabi** [comment]
@drakon5 Would you like to design that About page? Than i could try to fit it into the app.

Well yes is suspected that something went wrong, when someone told me that the features which where added with 0.4.2 are not working after i tagged the release. Hmpf it's the second time now that is messed up the version code -.-

**Comment by theScrabi** [comment]
So i released a new version, means i think its ok when i don't bother about 0.4.2 anymore.

**Comment by darkon5** [comment]
I'll make the VideoDetail redesign and the new About ASAP, I've been pretty busy (and struggling with GitHub) =P
