### ISSUE TITLE
[feature request] Continue playing video when device locks

### ISSUE THREAD

**Issue by medavox** [theScrabi/NewPipe#63]
I used to use different YouTube players (PVSTAR+, also uListen 1 and 2), in which I could play a video (usually music), then turn off the device's screen to save power.

This would be cool to have!

**Comment by theScrabi** [comment]
I think it would not be necessary. NewPipe can gather Audo only streams from videos. So you can download, or listen to them via VLC player. For the future I plan to stream audio directly via NP. Also audio only saves even more power, since you don't need to download the whole video file.

**Comment by theScrabi** [comment]
If you like and since you ask to help, you could try to implement the build in audio streaming.

**Comment by medavox** [comment]
OK, sounds good. I'll have a go once I've familiarised myself with the code

**Comment by theScrabi** [comment]
All right. If you have questions about the code, just ask (also via mail if you like).

**Comment by medavox** [comment]
This is the next thing I'll be implementing.

**Comment by theScrabi** [comment]
Hm cool. Could you make a player like interface, with a media controller as a notification, so we could control playing from the log screen. :) Would be nice.

**Comment by medavox** [comment]
I certainly will :) Although the latest Android Material guidelines state that using a specific lock screen widget is deprecated, and that I should implement this with a notification. So I will :)

**Comment by theScrabi** [comment]
Yes I meant a notification. xD nice work.

**Comment by PanderMusubi** [comment]
The current version from F-Droid does not continue playing when the device is locked. Could this please be reopened?

**Comment by Dostoi** [comment]
There's a listen in background feature since a few version.
 You have to press the headset button at the top of the video page (not sure if I'm clear enough)

**Comment by PanderMusubi** [comment]
Aaah. Yes, that is a bit hidden, even for advanced users. Can Play in background be started automatically when the app is pushed to background while playing something. Perhaps offer a setting similar to what WebTube has, so it does that only when that has been indicated in the settings by the user.

**Comment by BezMan** [comment]
Background/Popup buttons already shown on VideoDetailFragment class, before even entering VideoPlayer.
