### ISSUE TITLE
Network Error

### ISSUE THREAD

**Issue by 9662** [theScrabi/NewPipe#66]
On Android 4.2.1, no Google account or tools. If I open NewPipe and try to search for anything, I get a toast message saying "Network Error", and nothing else happens, apart from the little spinning circle going on forever.

If I tap on a video on the YouTube website, mobile version, Firefox, screen goes blank and that's it. If I switch to desktop version it works (in the browser, not in NewPipe). Not sure if this is related, thought I would mention it anyway.

**Comment by theScrabi** [comment]
I know where the error happens, but i don't know what happens. Anyway newpipe should print a stacktrace where it happens. Therefore id need a [Log](https://f-droid.org/repository/browse/?fdfilter=log&fdid=org.jtb.alogcat).

**Comment by theScrabi** [comment]
@9662 is that error still present?

**Comment by 9662** [comment]
@theScrabi No, with version 0.6.2 from F-Droid it is not there. I think I have an idea where the problem might have come from. I had disabled most pre-installed SSL certificates so the negotiation was failing. You can see more details in [another bug of mine](https://github.com/osmandapp/Osmand/issues/1837#issuecomment-166385835).

**Comment by 9662** [comment]
Version 0.7.0 also works fine.

Fantastic application, btw. Congratulations!!!
