### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by theScrabi** [theScrabi/NewPipe#69]
Translation is never a bad Idea :). I have recently opened the possibility to push changes from Weblate. Therefore you can translate NewPipe at this webiste:
https://hosted.weblate.org/projects/newpipe/strings/

**Comment by timofonic** [comment]
I might try to help with Spanish if I get less tired. I also want to help with KiCad, too.

**Comment by theScrabi** [comment]
All right sounds good.

PS: (I googled KiCad. I was searching for such a program quiet a while. @timofonc is it able to simulate analog/digital electrics circets? If so please lets continue this discussion via mail.)

**Comment by JasperWeiss** [comment]
I'll help out with Dutch

**Comment by theScrabi** [comment]
All right thanks.

**Comment by timofonic** [comment]
I translated to Spanish, it was already mostly translated. I did some changes.

There's too few strings to translate. I would prefer if someone reviews my changes ;)

**Comment by Dostoi** [comment]
Only one left in French

**Comment by theScrabi** [comment]
Nice work :)

**Comment by M2ck** [comment]
French translation almost done, I've need more context about strings n° 39 & 45 please.

**Comment by chschtsch** [comment]
You mean, 'Uploader thumbnail'? It's the avatar of an YouTube user.

**Comment by M2ck** [comment]
Yes, thanks. French translation completed!

**Comment by theScrabi** [comment]
I think this thread can be considered closed. Since WebLate translation is working pretty well.
