### ISSUE TITLE
[feature request] background play

### ISSUE THREAD

**Issue by leoauri** [theScrabi/NewPipe#8]
Unless I missed something, the play pauses if the app main screen is left (but continues if the screen phone is locked). Background play would be much appreciated for listening to music I don't need to see!
Thanks looks good

**Comment by daniell1** [comment]
Yeah, I can confirm that it plays while the screen is locked but it doesn't pause on any of my devices.

**Comment by theScrabi** [comment]
Hm right. For my own shame i need to say that the player was the last part I wrote, and I may have done it a bit sloppy. So yes the player will be reworked, and a "Listen to music" function will come to as son as i find time for it :)
