### ISSUE TITLE
Refactor Extractor to make site scraping steps more explicit

### ISSUE THREAD

**Issue by medavox** [theScrabi/NewPipe#83]
(copied from [here](https://github.com/theScrabi/NewPipe/issues/68#issuecomment-155770979) )

API-wise, I think it would be a good idea to split up `Extractor.getVideoInfo()` into a set of smaller interface methods, such as `getVideoTitle()` and `getDescription()`, so that implementing support for a new streaming service is more guided. Implementers would just write the individual extraction methods from the Extractor interface, which fill in each `VideoInfo` field.

That way, it's harder to forget to initialise a `VideoInfo` field when implementing new streaming services. It also allows each method to use fall-back scraping techniques, and abstract this away into a called method.

For instance, the view count on a Youtube video can be extracted from either the `<meta>` tag, or the `view_count` field in the JSON player args. If one fails, the other technique could be silently used instead.

**Comment by theScrabi** [comment]
@medavox sounds good. Lets elaborate this. Than at the end we could try to begin documenting the interfaces.

**Comment by medavox** [comment]
I've decided to put this on hold for now, and focus on feature development and bugfixing. This kind of refactoring work is too (low-priority | time-consuming | disruptive to other development), when there are still major features left to implement.


* Implementing support for other services will only happen a maximum of 10 more times, and these will all probably be by us. Making this step easier is not *that* high a priority.
* Having to implement try-catch blocks for every method won't reduce code duplication, it'll increase it.
* Although the try-catch blocks allow for trying multiple scraping techniques, in reality if the JSON technique fails, there's probably too major a problem to be recovered from anyway. The JSON player arguments contain the stream URL, after all.

Also, after having worked on this, I now feel giving `Extractor` a method per scraping event is too verbose. It doesn't improve code quality. Sorry for changing my mind, but the code didn't look good.

That's not to say that *some* refactoring work won't be taking place; it's just going to be secondary (for me) to feature dev. For now.

For instance, I'd like to rename `VideoInfoItem` to `VideoPreviewInfo`, as the class represents (AFAICT) a subset of the fields in `VideoInfo`, which are scraped from links to other videos on a given page. If one of these linked videos are clicked (eg related or next), then the `VideoInfoItem`'s info can be reused to create a full `VideoInfo`. Only the extra, unknown fields  would then need downloading for `VideoInfo`, speeding up video loading.

I'll push my refactoring changes so far to a separate branch, so you can see where I would have gone with Extractor. No point throwing away potentially reusable code.
