### ISSUE TITLE
[Feature request] Set default resolution of video playback

### ISSUE THREAD

**Issue by fred702** [theScrabi/NewPipe#9]
Some users may prefer to save bandwidth and CPU/battery life by choosing a lower quality stream or have devices with resolution under 720p

This app is incredible by the way, you should consider allowing donations.

**Comment by theScrabi** [comment]
So I've added a preference option, that lets you choose your favorite default resolution. I hope that was your intention :)

**Comment by fred702** [comment]
Yes, exactly! Thanks again.
