### ISSUE TITLE
Bug: back button not working properly play_video activity

### ISSUE THREAD

**Issue by JasperWeiss** [theScrabi/NewPipe#99]
When playing a video the back button first hides the video controls, the second time it goes back to video details. Whereas the backbutton at the top left corner does that immediately.
Basically you need to press back 2 times for it to work.
With on screen buttons, navigation controls are hidden when viewing a video, so when I tap the screen both the navigation controls show up and the video controls. When I hit back the video controls hide, then hit back a second time to actually go back.

**Comment by theScrabi** [comment]
Yes this is the default behavior of MediaController. I can't change it, unless we wrote our own video controls.

**Comment by JasperWeiss** [comment]
It's not the case with youtube though

**Comment by theScrabi** [comment]
Youtube app does not use the default MediaController.

**Comment by medavox** [comment]
I've implemented a fix for this, though it's in commits on the 'refactor' branch, after the pull request.
